package com.project.schale.saki.database.product.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Category implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.category_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.parent_category_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Long parentCategoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.name
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.create_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private LocalDateTime createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.update_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private LocalDateTime updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.depth
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Integer depth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table categories
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.category_id
     *
     * @return the value of categories.category_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.category_id
     *
     * @param categoryId the value for categories.category_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.parent_category_id
     *
     * @return the value of categories.parent_category_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Long getParentCategoryId() {
        return parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.parent_category_id
     *
     * @param parentCategoryId the value for categories.parent_category_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setParentCategoryId(Long parentCategoryId) {
        this.parentCategoryId = parentCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.name
     *
     * @return the value of categories.name
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.name
     *
     * @param name the value for categories.name
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.create_at
     *
     * @return the value of categories.create_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public LocalDateTime getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.create_at
     *
     * @param createAt the value for categories.create_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.update_at
     *
     * @return the value of categories.update_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public LocalDateTime getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.update_at
     *
     * @param updateAt the value for categories.update_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.depth
     *
     * @return the value of categories.depth
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Integer getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.depth
     *
     * @param depth the value for categories.depth
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setDepth(Integer depth) {
        this.depth = depth;
    }
}