package com.project.schale.saki.database.product.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Image implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.image_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Long imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.item_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.name
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.create_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private LocalDateTime createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column images.update_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private LocalDateTime updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.image_id
     *
     * @return the value of images.image_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Long getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.image_id
     *
     * @param imageId the value for images.image_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setImageId(Long imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.item_id
     *
     * @return the value of images.item_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.item_id
     *
     * @param itemId the value for images.item_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.name
     *
     * @return the value of images.name
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.name
     *
     * @param name the value for images.name
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.create_at
     *
     * @return the value of images.create_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public LocalDateTime getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.create_at
     *
     * @param createAt the value for images.create_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column images.update_at
     *
     * @return the value of images.update_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public LocalDateTime getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column images.update_at
     *
     * @param updateAt the value for images.update_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }
}