package com.project.schale.saki.database.product.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Item implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.name
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.shop_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Long shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.category_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.price
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.purchase_num
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Integer purchaseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.stock
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.is_stopped
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private Boolean isStopped;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.create_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private LocalDateTime createAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.update_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private LocalDateTime updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.description
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table items
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_id
     *
     * @return the value of items.item_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_id
     *
     * @param itemId the value for items.item_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.name
     *
     * @return the value of items.name
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.name
     *
     * @param name the value for items.name
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.shop_id
     *
     * @return the value of items.shop_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.shop_id
     *
     * @param shopId the value for items.shop_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.category_id
     *
     * @return the value of items.category_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.category_id
     *
     * @param categoryId the value for items.category_id
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.price
     *
     * @return the value of items.price
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.price
     *
     * @param price the value for items.price
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.purchase_num
     *
     * @return the value of items.purchase_num
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Integer getPurchaseNum() {
        return purchaseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.purchase_num
     *
     * @param purchaseNum the value for items.purchase_num
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setPurchaseNum(Integer purchaseNum) {
        this.purchaseNum = purchaseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.stock
     *
     * @return the value of items.stock
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.stock
     *
     * @param stock the value for items.stock
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.is_stopped
     *
     * @return the value of items.is_stopped
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public Boolean getIsStopped() {
        return isStopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.is_stopped
     *
     * @param isStopped the value for items.is_stopped
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setIsStopped(Boolean isStopped) {
        this.isStopped = isStopped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.create_at
     *
     * @return the value of items.create_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public LocalDateTime getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.create_at
     *
     * @param createAt the value for items.create_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setCreateAt(LocalDateTime createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.update_at
     *
     * @return the value of items.update_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public LocalDateTime getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.update_at
     *
     * @param updateAt the value for items.update_at
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setUpdateAt(LocalDateTime updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.description
     *
     * @return the value of items.description
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.description
     *
     * @param description the value for items.description
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}