package com.project.schale.saki.database.product.mapper;

import com.project.schale.saki.database.product.model.Image;
import com.project.schale.saki.database.product.model.ImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    @SelectProvider(type=ImageSqlProvider.class, method="countByExample")
    long countByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    @DeleteProvider(type=ImageSqlProvider.class, method="deleteByExample")
    int deleteByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    @Delete({
        "delete from images",
        "where image_id = #{imageId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Long imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    @Insert({
        "insert into images (image_id, item_id, ",
        "name, create_at, ",
        "update_at)",
        "values (#{imageId,jdbcType=INTEGER}, #{itemId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{createAt,jdbcType=TIMESTAMP}, ",
        "#{updateAt,jdbcType=TIMESTAMP})"
    })
    int insert(Image row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    @InsertProvider(type=ImageSqlProvider.class, method="insertSelective")
    int insertSelective(Image row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    @SelectProvider(type=ImageSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="image_id", property="imageId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="item_id", property="itemId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_at", property="createAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_at", property="updateAt", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Image> selectByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    @Select({
        "select",
        "image_id, item_id, name, create_at, update_at",
        "from images",
        "where image_id = #{imageId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="image_id", property="imageId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="item_id", property="itemId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_at", property="createAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_at", property="updateAt", jdbcType=JdbcType.TIMESTAMP)
    })
    Image selectByPrimaryKey(Long imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    @UpdateProvider(type=ImageSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") Image row, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    @UpdateProvider(type=ImageSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") Image row, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    @UpdateProvider(type=ImageSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Image row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table images
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    @Update({
        "update images",
        "set item_id = #{itemId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "create_at = #{createAt,jdbcType=TIMESTAMP},",
          "update_at = #{updateAt,jdbcType=TIMESTAMP}",
        "where image_id = #{imageId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Image row);
}