package com.project.schale.saki.database.product.mapper;

import com.project.schale.saki.database.product.model.Item;
import com.project.schale.saki.database.product.model.ItemExample.Criteria;
import com.project.schale.saki.database.product.model.ItemExample.Criterion;
import com.project.schale.saki.database.product.model.ItemExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ItemSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String countByExample(ItemExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("items");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String deleteByExample(ItemExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("items");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String insertSelective(Item row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("items");
        
        if (row.getItemId() != null) {
            sql.VALUES("item_id", "#{itemId,jdbcType=INTEGER}");
        }
        
        if (row.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (row.getShopId() != null) {
            sql.VALUES("shop_id", "#{shopId,jdbcType=INTEGER}");
        }
        
        if (row.getCategoryId() != null) {
            sql.VALUES("category_id", "#{categoryId,jdbcType=INTEGER}");
        }
        
        if (row.getPrice() != null) {
            sql.VALUES("price", "#{price,jdbcType=INTEGER}");
        }
        
        if (row.getPurchaseNum() != null) {
            sql.VALUES("purchase_num", "#{purchaseNum,jdbcType=INTEGER}");
        }
        
        if (row.getStock() != null) {
            sql.VALUES("stock", "#{stock,jdbcType=INTEGER}");
        }
        
        if (row.getIsStopped() != null) {
            sql.VALUES("is_stopped", "#{isStopped,jdbcType=BIT}");
        }
        
        if (row.getCreateAt() != null) {
            sql.VALUES("create_at", "#{createAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getUpdateAt() != null) {
            sql.VALUES("update_at", "#{updateAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String selectByExampleWithBLOBs(ItemExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("item_id");
        } else {
            sql.SELECT("item_id");
        }
        sql.SELECT("name");
        sql.SELECT("shop_id");
        sql.SELECT("category_id");
        sql.SELECT("price");
        sql.SELECT("purchase_num");
        sql.SELECT("stock");
        sql.SELECT("is_stopped");
        sql.SELECT("create_at");
        sql.SELECT("update_at");
        sql.SELECT("description");
        sql.FROM("items");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String selectByExample(ItemExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("item_id");
        } else {
            sql.SELECT("item_id");
        }
        sql.SELECT("name");
        sql.SELECT("shop_id");
        sql.SELECT("category_id");
        sql.SELECT("price");
        sql.SELECT("purchase_num");
        sql.SELECT("stock");
        sql.SELECT("is_stopped");
        sql.SELECT("create_at");
        sql.SELECT("update_at");
        sql.FROM("items");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Item row = (Item) parameter.get("row");
        ItemExample example = (ItemExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("items");
        
        if (row.getItemId() != null) {
            sql.SET("item_id = #{row.itemId,jdbcType=INTEGER}");
        }
        
        if (row.getName() != null) {
            sql.SET("name = #{row.name,jdbcType=VARCHAR}");
        }
        
        if (row.getShopId() != null) {
            sql.SET("shop_id = #{row.shopId,jdbcType=INTEGER}");
        }
        
        if (row.getCategoryId() != null) {
            sql.SET("category_id = #{row.categoryId,jdbcType=INTEGER}");
        }
        
        if (row.getPrice() != null) {
            sql.SET("price = #{row.price,jdbcType=INTEGER}");
        }
        
        if (row.getPurchaseNum() != null) {
            sql.SET("purchase_num = #{row.purchaseNum,jdbcType=INTEGER}");
        }
        
        if (row.getStock() != null) {
            sql.SET("stock = #{row.stock,jdbcType=INTEGER}");
        }
        
        if (row.getIsStopped() != null) {
            sql.SET("is_stopped = #{row.isStopped,jdbcType=BIT}");
        }
        
        if (row.getCreateAt() != null) {
            sql.SET("create_at = #{row.createAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getUpdateAt() != null) {
            sql.SET("update_at = #{row.updateAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getDescription() != null) {
            sql.SET("description = #{row.description,jdbcType=LONGVARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("items");
        
        sql.SET("item_id = #{row.itemId,jdbcType=INTEGER}");
        sql.SET("name = #{row.name,jdbcType=VARCHAR}");
        sql.SET("shop_id = #{row.shopId,jdbcType=INTEGER}");
        sql.SET("category_id = #{row.categoryId,jdbcType=INTEGER}");
        sql.SET("price = #{row.price,jdbcType=INTEGER}");
        sql.SET("purchase_num = #{row.purchaseNum,jdbcType=INTEGER}");
        sql.SET("stock = #{row.stock,jdbcType=INTEGER}");
        sql.SET("is_stopped = #{row.isStopped,jdbcType=BIT}");
        sql.SET("create_at = #{row.createAt,jdbcType=TIMESTAMP}");
        sql.SET("update_at = #{row.updateAt,jdbcType=TIMESTAMP}");
        sql.SET("description = #{row.description,jdbcType=LONGVARCHAR}");
        
        ItemExample example = (ItemExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("items");
        
        sql.SET("item_id = #{row.itemId,jdbcType=INTEGER}");
        sql.SET("name = #{row.name,jdbcType=VARCHAR}");
        sql.SET("shop_id = #{row.shopId,jdbcType=INTEGER}");
        sql.SET("category_id = #{row.categoryId,jdbcType=INTEGER}");
        sql.SET("price = #{row.price,jdbcType=INTEGER}");
        sql.SET("purchase_num = #{row.purchaseNum,jdbcType=INTEGER}");
        sql.SET("stock = #{row.stock,jdbcType=INTEGER}");
        sql.SET("is_stopped = #{row.isStopped,jdbcType=BIT}");
        sql.SET("create_at = #{row.createAt,jdbcType=TIMESTAMP}");
        sql.SET("update_at = #{row.updateAt,jdbcType=TIMESTAMP}");
        
        ItemExample example = (ItemExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    public String updateByPrimaryKeySelective(Item row) {
        SQL sql = new SQL();
        sql.UPDATE("items");
        
        if (row.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (row.getShopId() != null) {
            sql.SET("shop_id = #{shopId,jdbcType=INTEGER}");
        }
        
        if (row.getCategoryId() != null) {
            sql.SET("category_id = #{categoryId,jdbcType=INTEGER}");
        }
        
        if (row.getPrice() != null) {
            sql.SET("price = #{price,jdbcType=INTEGER}");
        }
        
        if (row.getPurchaseNum() != null) {
            sql.SET("purchase_num = #{purchaseNum,jdbcType=INTEGER}");
        }
        
        if (row.getStock() != null) {
            sql.SET("stock = #{stock,jdbcType=INTEGER}");
        }
        
        if (row.getIsStopped() != null) {
            sql.SET("is_stopped = #{isStopped,jdbcType=BIT}");
        }
        
        if (row.getCreateAt() != null) {
            sql.SET("create_at = #{createAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getUpdateAt() != null) {
            sql.SET("update_at = #{updateAt,jdbcType=TIMESTAMP}");
        }
        
        if (row.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("item_id = #{itemId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items
     *
     * @mbg.generated Mon Oct 21 22:15:08 JST 2024
     */
    protected void applyWhere(SQL sql, ItemExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}